### ISSUE TITLE
Unescaped $keys can cause cause regex error

### ISSUE THREAD

**Issue by TestingBytes** [ollyg/App-iosdiff#1]
When the ios config contains characters that look like regex modifiers (like bunch of *s, for example), iosdiff dies on line 135 with this error:

Nested quantifiers in regex; marked by <-- HERE in m/^*\* <-- HERE ****************************************************************************************\* / at /usr/local/share/perl/5.20.2/App/iosdiff.pm line 135.

This can be resolved by adding quote and end quotes to the regex statement. This is fixed in pull request #2.

**Comment by ollyg** [comment]
Thanks, version 1.200001 on its way to CPAN now.
